# src/gog_fraud/pipelines/run_tuning_workflow.py
import subprocess
import os
import json
import logging
from pathlib import Path

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
logger = logging.getLogger("MasterWorkflow")

def run_cmd(cmd, cwd="."):
    logger.info(f"Running: {' '.join(cmd)}")
    result = subprocess.run(cmd, cwd=cwd, env={**os.environ, "PYTHONPATH": "src"})
    if result.returncode != 0:
        logger.error(f"Command failed with return code {result.returncode}")
        return False
    return True

def run_workflow():
    py_exec = "/mnt/d/_Work/MC_and_nGNN_for_GoG/.venv/bin/python3"
    out_dir = "docs/work_reports/legacy_param_search/"
    legacy_results_dir = "../_data/results"
    
    # 1. Phase 1: Coarse Screening
    logger.info("=== Phase 1: Coarse Screening (SKIPPED per user request) ===")
    # p1_dir = os.path.join(out_dir, "phase1")
    # os.makedirs(p1_dir, exist_ok=True)
    # p1_cmd = [
    #     py_exec, "src/gog_fraud/pipelines/search_legacy_params.py",
    #     "--chains", "bsc,ethereum,polygon",
    #     "--workers", "8",
    #     "--gpu_limit", "1",
    #     "--coarse",
    #     "--out_dir", p1_dir
    # ]
    # if not run_cmd(p1_cmd):
    #     return

    # 2. Phase 2: Refinement
    logger.info("=== Phase 2: Refinement (SKIPPED per user request) ===")
    # p2_dir = os.path.join(out_dir, "phase2")
    # os.makedirs(p2_dir, exist_ok=True)
    # for chain in ["bsc", "ethereum", "polygon"]:
    #     p1_best_file = Path(f"configs/legacy/best_params/best_params_{chain}.json")
    #     if not p1_best_file.exists():
    #         logger.warning(f"No Phase 1 best file for {chain}. Skipping refinement.")
    #         continue
    #     p2_cmd = [
    #         py_exec, "src/gog_fraud/pipelines/search_legacy_params.py",
    #         "--chains", chain,
    #         "--workers", "8",
    #         "--gpu_limit", "1",
    #         "--refine_from", str(p1_best_file),
    #         "--out_dir", p2_dir
    #     ]
    #     if not run_cmd(p2_cmd):
    #         logger.error(f"Refinement failed for {chain}")

    # 3. Stage 3: Final Comparative Benchmark (Revision models)
    logger.info("=== Stage 3: Final Comparative Benchmark (Revision Models) ===")
    # Note: We keep this to run nGNN, Level 1, and Level 2 benchmarks.
    bench_cmd = [
        py_exec, "src/gog_fraud/pipelines/run_fraud_benchmark.py"
    ]
    run_cmd(bench_cmd)

    # 4. Stage 4: Results Consolidation & Reporting
    logger.info("=== Stage 4: Results Consolidation & Reporting ===")
    consolidate_results(legacy_results_dir, "benchmark_results.json", os.path.join(out_dir, "final_report.md"))

    logger.info("Master Workflow Completed.")

def consolidate_results(legacy_dir: str, revision_file: str, report_path: str):
    import pandas as pd
    from pathlib import Path
    
    chains = ["bsc", "ethereum", "polygon"]
    all_data = []

    # 1. Load Legacy Results
    for chain in chains:
        legacy_file = Path(legacy_dir) / f"benchmark_results_{chain}.json"
        if legacy_file.exists():
            with open(legacy_file, 'r') as f:
                data = json.load(f)
                for row in data:
                    row["chain"] = chain.upper()
                    all_data.append(row)
        else:
            logger.warning(f"Legacy result not found: {legacy_file}")

    # 2. Load Revision Results (if generated by Stage 3)
    # run_fraud_benchmark.py usually saves to 'benchmark_results.json' in the current or output dir
    rev_p = Path(revision_file)
    if rev_p.exists():
        with open(rev_p, 'r') as f:
            data = json.load(f)
            # Revisions usually contain multiple chains if run cross-network
            for row in data:
                # If chain not in row, we might need to infer it or just tag as REVISION
                if "chain" not in row: row["chain"] = "MULTI"
                all_data.append(row)
    else:
        logger.warning(f"Revision benchmark result not found: {revision_file}")

    if not all_data:
        logger.error("No results found to consolidate.")
        return

    df = pd.DataFrame(all_data)
    # Re-order columns for readability
    cols = ["chain", "model_name", "roc_auc", "pr_auc", "best_f1"]
    existing_cols = [c for c in cols if c in df.columns]
    df = df[existing_cols]
    
    # Generate Markdown Report
    os.makedirs(os.path.dirname(report_path), exist_ok=True)
    with open(report_path, "w") as f:
        f.write("# Final Fraud Pipeline Benchmark Report\n\n")
        f.write("Generated from consolidated legacy and revision model results.\n\n")
        f.write(df.to_markdown(index=False))
        f.write("\n\n---\n*End of Report*\n")

    logger.info(f"Final report saved to: {report_path}")
    print("\n" + df.to_markdown(index=False))

if __name__ == "__main__":
    run_workflow()
